version: '3'

services:
  testlink:
    image: 'bitnami/testlink:latest'
    env_file:
      - './.env'
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - "./testlink:/bitnami/testlink"